routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use phpDocumentor\Reflection\Types\Resource_;
use App\Http\Controllers\AgendaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/autor', function () {
    return view('autor');
});
Route::resource('/agendas', AgendaController::class);

app/Models/Agenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    use HasFactory;
    protected $fillable = ['nombres', 'apellidos', 'celular', 'email', 'direccion'];   
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AgendaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Agenda;
use Illuminate\Http\Request;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $agendas = Agenda::get();
        
        return view('agenda.index', 
            [
                'agendas' => $agendas
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('agenda.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $agenda = new Agenda();
        $agenda->nombres = $request->nombres;
        $agenda->apellidos = $request->apellidos;
        $agenda->celular = $request->celular;
        $agenda->email = $request->email;
        $agenda->direccion = $request->direccion;
        $agenda->save();
        
        return redirect()->route('agendas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function show(Agenda $agenda)
    {
        return view('agenda.show', 
            [
                'agenda' => $agenda
            ]
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function edit(Agenda $agenda)
    {
        return view('agenda.edit', 
            [
                'agenda' => $agenda
            ]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agenda $agenda)
    {
        $agenda->nombres = $request->nombres;
        $agenda->apellidos = $request->apellidos;
        $agenda->celular = $request->celular;
        $agenda->email = $request->email;
        $agenda->direccion = $request->direccion;
        $agenda->save();
        
        return redirect()->route('agendas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Agenda  $agenda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agenda $agenda)
    {
        $agenda->delete();
        
        return redirect()->route('agendas.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/agenda/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar</title>
</head>
<body>
    <form action="{{route('agendas.store')}}" method="POST">
        @csrf
        <input type="text" name="nombres" placeholder="Nombres"><br>
        <input type="text" name="apellidos" placeholder="Apellidos"><br>
        <input type="number" name="celular" placeholder="Celular"><br>
        <input type="email" name="email" placeholder="Email"><br>
        <input type="text" name="direccion" placeholder="Direccion"><br>
        <input type="submit" value="Insertar">

    </form>
    
</body>
</html>

resources/views/agenda/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar</title>
</head>
<body>
    <form action="{{route('agendas.update',$agenda->id)}}" method="POST">
        @csrf
        @method('PUT')
        <input type="text" name="nombres" placeholder="Nombres" value="{{$agenda->nombres}}"><br>
        <input type="text" name="apellidos" placeholder="Apellidos" value="{{$agenda->apellidos}}"><br>
        <input type="number" name="celular" placeholder="Celular" value="{{$agenda->celular}}"><br>
        <input type="email" name="email" placeholder="Email" value="{{$agenda->email}}"><br>
        <input type="text" name="direccion" placeholder="Direccion" value="{{$agenda->direccion}}"><br>
        <input type="submit" value="Editar">

    </form>
    
</body>
</html>

resources/views/agenda/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar</title>
</head>
<body>
    
    <table>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Celular</th>
            <th>Email</th>
            <th>Direccion</th>
            <th>Acciones</th>
        </tr>
        @foreach($agendas as $agenda)
        <tr>
            <td>{{$agenda->nombres}}</td>
            <td>{{$agenda->apellidos}}</td>
            <td>{{$agenda->celular}}</td>
            <td>{{$agenda->email}}</td>
            <td>{{$agenda->direccion}}</td>
            <td>
                <a href="{{route('agendas.edit', $agenda->id)}}">Editar</a>
                <a href="{{route('agendas.show', $agenda->id)}}">Mostrar</a>
                <form action="{{route('agendas.destroy', $agenda->id)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="Eliminar">
                </form>
                
        </tr>
        @endforeach
    </table>
    <a href="{{route('agendas.create')}}">Insertar</a>
    
</body>
</html>

resources/views/agenda/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listar</title>
</head>
<body>
    <ul>
        <li>{{$agenda->nombres}}</li>
        <li>{{$agenda->apellidos}}</li>
        <li>{{$agenda->celular}}</li>
        <li>{{$agenda->direccion}}</li>

        </ul>

        <a href="{{route('agendas.edit', $agenda->id)}}">Editar</a>
    <a href="{{route('agendas.index', $agenda->id)}}">Listar</a>
</body>
</html>